<?php
/**
 * AssetLoader Utility Class
 *
 * Provides static methods to enqueue scripts and styles with WordPress.
 * Automatically handles .asset.php metadata files generated by build tools like wp-scripts.
 * Falls back to file modification time for versioning if asset metadata is not available.
 *
 * Usage:
 *     AssetLoader::enqueue_script( 'my-handle', 'assets/js/my-script.js', __FILE__ );
 *     AssetLoader::enqueue_style( 'my-style', 'assets/css/my-style.css', __FILE__ );
 *
 * @package YourPluginNamespace\Utils
 */

namespace SnapchatForWooCommerce\Utils;

use SnapchatForWooCommerce\Config;

/**
 * Class AssetLoader
 *
 * A utility class for registering and enqueuing assets (scripts and styles)
 * in a WordPress plugin or theme, with support for asset metadata files.
 */
class AssetLoader {
	/**
	 * Enqueue a script using a script path and its asset metadata.
	 *
	 * @since 0.1.0
	 *
	 * @param string $handle    The handle for the script.
	 * @param string $file_name The relative path to the script file
	 */
	public static function enqueue_script( $handle, $file_name ) {
		$script_path       = SNAPCHAT_ADS_PLUGIN_BUILD_PATH . $file_name;
		$script_url        = SNAPCHAT_ADS_PLUGIN_BUILD_URL . $file_name;
		$script_asset_path = $script_path . '.asset.php';

		if ( file_exists( $script_asset_path ) ) {
			$asset_data = require $script_asset_path;
		} else {
			$asset_data = array(
				'dependencies' => array(),
				'version'      => filemtime( $script_path ),
			);
		}

		wp_enqueue_script(
			Config::ASSET_HANDLE_PREFIX . $handle,
			$script_url,
			$asset_data['dependencies'],
			$asset_data['version'],
			true
		);
	}

	/**
	 * Enqueue a style using a style path and its asset metadata.
	 *
	 * @since 0.1.0
	 *
	 * @param string $handle    The handle for the style.
	 * @param string $file_name The relative path to the style file.
	 */
	public static function enqueue_style( $handle, $file_name ) {
		$style_path       = SNAPCHAT_ADS_PLUGIN_BUILD_PATH . $file_name;
		$style_url        = SNAPCHAT_ADS_PLUGIN_BUILD_URL . $file_name;
		$style_asset_path = $style_path . '.asset.php';

		if ( file_exists( $style_asset_path ) ) {
			$asset_data = require $style_asset_path;
		} else {
			$asset_data = array(
				'dependencies' => array(),
				'version'      => filemtime( $style_path ),
			);
		}

		wp_enqueue_style(
			Config::ASSET_HANDLE_PREFIX . $handle,
			$style_url,
			$asset_data['dependencies'],
			$asset_data['version']
		);
	}
}
