/**
 * Internal Dependencies.
 */
import { TRACKING_DATA_VAR } from '../constants';
import { SnapchatEvent } from './events';

/**
 * Track an event using the global snaptr function.
 *
 * @since 0.1.0
 *
 * @param {string} eventName
 * @param {Object} eventParams
 * @throws Will throw an error if the global snaptr function is not available.
 */
export const trackEvent = ( eventName, eventParams ) => {
	if ( typeof snaptr !== 'function' ) {
		throw new Error( 'Function snaptr not implemented.' );
	}

	window.snaptr( 'track', eventName, {
		...eventParams,
	} );
};

/**
 * Handle add to cart clicks for single product pages.
 *
 * @since 0.1.0
 *
 * @param {Object} event Generated by addEventListener.
 * @param {string} eventId Unique UUID event ID.
 */
export const singleAddToCartClick = function ( event, eventId = '' ) {
	const cartForm = event.target.closest( 'form.cart' );

	if ( ! cartForm ) {
		return;
	}

	const addToCart = cartForm.querySelector( '[name=add-to-cart]' );
	if ( ! addToCart ) {
		return;
	}

	const variationId = cartForm.querySelector( '[name=variation_id]' );
	const quantity = cartForm.querySelector( '[name=quantity]' );

	const product = getProductObject( {
		id: parseInt( variationId ? variationId.value : addToCart.value, 10 ),
	} );

	trackAddToCartEvent(
		product,
		quantity ? parseInt( quantity.value, 10 ) : 1,
		eventId
	);
};

/**
 * Handle add to cart clicks on any buttons shown in an archive loop.
 *
 * @since 0.1.0
 *
 * @param {Object} event Generated by addEventListener.
 * @param {string} eventId Unique UUID event ID.
 * @return {Object} product
 */
export const addToCartClick = function ( event, eventId = '' ) {
	const data = event.currentTarget.dataset;
	const product = getProductObject( { id: data.product_id } );

	trackAddToCartEvent( product, data.quantity || 1, eventId );
};

/**
 * Track an add_to_cart event.
 *
 * @since 0.1.0
 *
 * @param {Product} product
 * @param {number} quantity
 * @param {string|null} eventId
 */
const trackAddToCartEvent = ( product, quantity = 1, eventId = null ) => {
	const { id, price } = getCartItemObject( product, quantity );

	const data = {
		item_ids: [ id ],
		number_items: parseInt( quantity ),
		price,
	};

	if ( eventId ) {
		data.event_id        = eventId;
		data.client_dedup_id = eventId;
	}

	trackEvent( SnapchatEvent.ADD_CART, data );
};

/**
 * Formats a regular price into a price object.
 *
 * @since 0.1.0
 *
 * @param {number} price
 * @return {ProductPrices} Price object.
 */
const getPriceObject = ( price ) => {
	return {
		price: Math.round( price * 10 ** TRACKING_DATA_VAR.pixel_data.currency_minor_unit ),
		currency_minor_unit: TRACKING_DATA_VAR.pixel_data.currency_minor_unit,
	};
};

/**
 * Formats a product object to include price from global data.
 *
 * @since 0.1.0
 *
 * @param {Product} product
 * @return {Product} Product object with optional fields added.
 */
const getProductObject = ( product ) => {
	if ( TRACKING_DATA_VAR.pixel_data.products[ product.id ] ) {
		product.prices = getPriceObject(
			TRACKING_DATA_VAR.pixel_data.products[ product.id ].price
		);
	}
	return product;
};

/**
 * Updates product data with the retrieved variation.
 *
 * @since 0.1.0
 *
 * @param {Variation} variation
 */
export const retrievedVariation = ( variation ) => {
	if ( ! variation?.variation_id ) {
		return;
	}

	TRACKING_DATA_VAR.pixel_data.products[ variation.variation_id ] = {
		price: variation.display_price,
	};
};

/**
 * Formats data into a cart Item object.
 *
 * @since 0.1.0
 *
 * @param {Product} product
 * @param {number} quantity
 * @return {Item} Item object.
 */
export const getCartItemObject = ( product, quantity ) => {
	const item = {
		id: product.id,
		quantity,
	};

	if ( product?.prices?.price ) {
		item.price =
			parseInt( product.prices.price, 10 ) /
			10 ** product.prices.currency_minor_unit;
	}

	return item;
};