name: Build

on:
  workflow_call:
  push:
    branches:
      - trunk
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildExtensionBundle:
    name: Build extension bundle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@e981c25267d29c39ff6ab1ae4ea09b267efae86c # actions-v3.0.6
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@e981c25267d29c39ff6ab1ae4ea09b267efae86c # actions-v3.0.6
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      - name: Publish dev build to GitHub
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        uses: woocommerce/grow/publish-extension-dev-build@e981c25267d29c39ff6ab1ae4ea09b267efae86c # actions-v3.0.6
        with:
          extension-asset-path: snapchat-for-woocommerce.zip

      - name: Publish build artifact
        if: ${{ ! ( github.event_name == 'push' && github.ref_name == 'develop' ) }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snapchat-for-woocommerce.zip
          path: ${{ github.workspace }}/snapchat-for-woocommerce.zip
          # Do not bloat the storage. Keep in only long enough for a caller workflow to pick it up and follow up with some manual debugging.
          retention-days: 2
