name: E2E Tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  E2eTests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@actions-v2
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v2
        with:
          node-version-file: ".nvmrc"

      - name: Build production bundle
        run: npm run build

      - name: Start wp-env
        run: npm run env:start

      - name: Download and install Chromium browser.
        run: npx playwright install chromium

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Archive e2e failure screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
            name: e2e-screenshots
            path: tests/e2e/test-results/report/**/*.png
            if-no-files-found: ignore
            retention-days: 5
