name: E2E Tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:
    # We include `labeled` so adding the label re-triggers the workflow.
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  E2eTests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 2

    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: '.nvmrc'

      - name: Composer cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            vendor
            ~/.composer/cache
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Node cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: |
            node_modules
            ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Node install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Set WordPress RC version
        if: "${{ contains(github.event.pull_request.labels.*.name, 'needs: WP RC test') }}"
        run: ./tests/e2e/bin/set-core-version.js WordPress/WordPress#master

      - name: Setup WP environment
        run: npm run env:start

      - name: Check if the site is running
        run: curl -I http://localhost:8889

      - name: Run E2E tests
        id: e2e_tests
        run: npm run test:e2e

      # Update label on SUCCESS (PRs only)
      - name: Update Success Label
        if: |
          github.event_name == 'pull_request' &&
          always() &&
          steps.e2e_tests.conclusion == 'success'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['status: e2e tests failing']
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests passing']
            })

      # Update label on FAILURE (PRs only)
      - name: Update Failure Label
        if: |
          github.event_name == 'pull_request' &&
          always() &&
          steps.e2e_tests.conclusion == 'failure'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['status: e2e tests passing']
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests failing']
            })

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        if: always()
        with:
          name: playwright-report
          path: tests/e2e/test-results/report
          retention-days: 2
