name: PHP Coding Standards

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml
  pull_request:
    paths:
      - "**.php"
      - .github/workflows/php-coding-standards.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@da5279aa4d76745ef32970e49b5ef7903a3b457a # v2.2.2
        with:
          tools: cs2pr

      - name: Log PHPCS information
        run: vendor/bin/phpcs -i

      - name: Run PHPCS on all files
        run: vendor/bin/phpcs ./* -q --report=checkstyle | cs2pr

